source 'https://rubygems.org'

gem 'ffi'
gem 'cocoapods', '> 1.11.0'
gem 'fastlane'
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
